library(proto)
library(knitr)
library(xml2)
library(rvest)
library(gsubfn)
library(reshape2)
library(shiny)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(maptools)
library(rgdal)
library(rgeos)
library(ggvis)
library(GGally)

# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")
